%%{init: {'flowchart': {'curve': 'linear'}}}%%
flowchart TD
    A([Вход по CMD_DUMP]) --> B[Сохранить параметры команды]
    B --> C[Выбрать банк NAND1 или NAND2]
    C --> D[Включить питание выбранного банка<br/>если требуется]
    D --> E[Подтвердить наличие питания банка]
    E --> F[Определить число пакетов к передаче]
    F --> G[Подготовить интерфейс USB]
    G --> H[Проверить наличие VBUS]
    H --> I[Сформировать ТС 'Статус']
    I --> J[Начать цикл вывода]

    J --> K[Считать пакет 2048 байт из NAND]
    K --> L{"Пакет считан?"}
    L -- Да --> M[Передать пакет по USB]
    L -- Нет --> ZA[Аварийное завершение]

    K -. "Ошибка чтения<br/>или ошибка QSPI" .-> ZA
    K -. "CMD_DUTY" .-> Y[Завершение по команде]
    K -. "CMD_SHUTDOWN" .-> X[Завершение с переходом в SHUTDOWN]
    K -. "MaskedAlarm != 0" .-> ZA

    M --> N{"Передача завершена?"}
    N -- Да --> O[Увеличить счётчик переданных пакетов]
    N -- Нет --> M

    M -. "Ошибка передачи<br/>или нет VBUS" .-> P[Повтор передачи текущего пакета]
    M -. "CMD_DUTY" .-> Y
    M -. "CMD_SHUTDOWN" .-> X
    M -. "MaskedAlarm != 0" .-> ZA

    P --> P1{"Повтор успешен?"}
    P1 -- Да --> O
    P1 -- Нет --> ZA

    O --> Q{"Вывод завершён?"}
    Q -- Да --> Z[Штатное завершение]
    Q -- Нет --> J

    O -. "CMD_DUTY" .-> Y
    O -. "CMD_SHUTDOWN" .-> X
    O -. "MaskedAlarm != 0" .-> ZA

    Z --> Z1[Зафиксировать число переданных пакетов]
    Z1 --> Z2[Обновить счётчик последнего выведенного пакета]
    Z2 --> Z3["Оставить питание банка включённым<br/>или отключить по команде"]
    Z3 --> Z4["Сформировать ТС 'Статус'"]
    Z4 --> Z5([Выход из DUMP в DUTY])

    Y --> Y1["Завершить режим по принятому правилу<br/>досрочного завершения"]
    Y1 --> Y2["Оставить питание банка включённым<br/>или отключить по правилу выхода"]
    Y2 --> Y3["Сформировать ТС 'Статус'"]
    Y3 --> Y4([Выход из DUMP в DUTY])

    X --> X1["Завершить режим по принятому правилу<br/>выхода в SHUTDOWN"]
    X1 --> X2["Оставить питание банка включённым<br/>или отключить по правилу выхода"]
    X2 --> X3["Сформировать ТС 'Статус'"]
    X3 --> X4([Выход из DUMP в SHUTDOWN])

    ZA --> ZA1[Прекратить вывод данных]
    ZA1 --> ZA2[Отключить питание ПЭД]
    ZA2 --> ZA3[Отключить питание NAND1]
    ZA3 --> ZA4[Отключить питание NAND2]
    ZA4 --> ZA5["Сформировать ТС 'Статус'"]
    ZA5 --> ZA6([Выход из DUMP в ALARM])