flowchart TD
    A([Вход по CMD_DUMP]) --> B[Сохранить параметры команды]
    B --> C[Выбрать банк NAND1 или NAND2]
    C --> D[Включить питание выбранного банка<br/>если оно выключено]
    D --> E[Подтвердить наличие питания банка<br/>по PU_NANDx_PSON]
    E --> E1[Подключить сигнальные линии банка NAND к портам МК]
    E1 --> F[Определить число пакетов к передаче]
    F --> G[Проверить наличие VBUS]
    G --> H[Подключить линии USB к портам МК<br/>и подготовить интерфейс USB]
    H --> I[Сформировать ТС 'Статус']
    I --> J[Начать цикл вывода]

    J --> K[Считать пакет 2048 байт из NAND]
    K --> L{"Пакет считан?"}
    L -- Да --> M[Передать пакет по USB]
    L -- Нет --> ZA[Аварийное завершение]

    K -. "Ошибка чтения<br/>или ошибка интерфейса NAND" .-> ZA
    K -. "Потеря питания банка" .-> ZA
    K -. "CMD_DUTY" .-> Y[Завершение по команде]
    K -. "CMD_SHUTDOWN" .-> X[Завершение с переходом в SHUTDOWN]
    K -. "MaskedAlarm != 0" .-> ZA

    M --> N{"Передача завершена?"}
    N -- Да --> O[Увеличить счётчик переданных пакетов<br/>и обновить last_dumped_packet]
    N -- Нет --> M

    M -. "Ошибка передачи<br/>или ошибка интерфейса USB" .-> P[Повтор передачи текущего пакета]
    M -. "Нет VBUS" .-> ZA
    M -. "CMD_DUTY" .-> Y
    M -. "CMD_SHUTDOWN" .-> X
    M -. "MaskedAlarm != 0" .-> ZA

    P --> P1{"Повтор успешен?"}
    P1 -- Да --> O
    P1 -- Нет --> ZA

    O --> Q{"Вывод завершён?"}
    Q -- Да --> Z[Штатное завершение]
    Q -- Нет --> J

    O -. "CMD_DUTY" .-> Y
    O -. "CMD_SHUTDOWN" .-> X
    O -. "MaskedAlarm != 0" .-> ZA

    Z --> Z1[Зафиксировать число переданных пакетов]
    Z1 --> Z2[Записать служебные данные режима в MRAM]
    Z2 --> Z3{"Отключить питание банка?"}
    Z3 -- Да --> Z4[Отключить питание выбранного банка<br/>и отсоединить его линии от портов]
    Z3 -- Нет --> Z5[Сохранить питание выбранного банка]
    Z4 --> Z6[Отключить линии USB от портов]
    Z5 --> Z6
    Z6 --> Z7["Сформировать ТС 'Статус'"]
    Z7 --> Z8([Выход из DUMP в DUTY])

    Y --> Y1["Завершить передачу текущего пакета<br/>если она уже начата"]
    Y1 --> Y2[Обновить last_dumped_packet в MRAM]
    Y2 --> Y3{"Отключить питание банка?"}
    Y3 -- Да --> Y4[Отключить питание выбранного банка<br/>и отсоединить его линии от портов]
    Y3 -- Нет --> Y5[Сохранить питание выбранного банка]
    Y4 --> Y6[Отключить линии USB от портов]
    Y5 --> Y6
    Y6 --> Y7["Сформировать ТС 'Статус'"]
    Y7 --> Y8([Выход из DUMP в DUTY])

    X --> X1["Завершить передачу текущего пакета<br/>если она уже начата"]
    X1 --> X2[Обновить last_dumped_packet в MRAM]
    X2 --> X3[Отключить линии USB от портов]
    X3 --> X4["Передать управление режиму SHUTDOWN"]
    X4 --> X5([Выход из DUMP в SHUTDOWN])

    ZA --> ZA1[Прекратить вывод данных]
    ZA1 --> ZA2[Отключить линии USB от портов]
    ZA2 --> ZA3[Отключить питание ПЭД]
    ZA3 --> ZA4[Отключить питание NAND1]
    ZA4 --> ZA5[Отключить питание NAND2]
    ZA5 --> ZA6["Сформировать ТС 'Статус'"]
    ZA6 --> ZA7([Выход из DUMP в ALARM])