flowchart TD
    A([Вход по КУ 9<br/>CMD_ERASE]) --> B[Сохранить параметры КУ]
    B --> C[Выбрать банк NAND1 или NAND2]
    C --> D[Включить питание банка<br/>если требуется]
    D --> E[Дождаться PSON<br/>если требуется]
    E --> F{"Подготовка завершена<br/>MaskedAlarm == 0"}

    F -- Да --> G[Инициализировать сервис NAND]
    F -- Нет --> ZA[Завершение по аварии]

    G --> H[Запустить стирание]
    H --> I{"Запуск успешен"}

    I -- Да --> J[Ожидание завершения]
    I -- Нет --> ZA

    J --> K{"Событие в режиме стирания"}

    K -- "КУ 2<br/>CMD_STATUS_REQ" --> L[Сформировать ТС 'Статус']
    K -- "ERASE_DONE" --> Z[Штатное завершение]

    K -. "КУ 6<br/>CMD_DUTY" .-> Y[Завершение по команде]
    K -. "КУ 12<br/>CMD_SHUTDOWN" .-> Y
    K -. "Ошибка стирания<br/>или ошибка QSPI" .-> ZA
    K -. "MaskedAlarm != 0" .-> ZA

    L --> J

    Z --> Z1[Обновить состояние банка]
    Z1 --> Z2["Сбросить флаг переполнения<br/>если принято"]
    Z2 --> Z3["Счетчик стираний++"]
    Z3 --> Z4["Обновить MRAM<br/>если требуется"]
    Z4 --> Z5["Оставить питание банка<br/>или выключить по КУ"]
    Z5 --> Z6([Выход из режима стирания])

    Y --> Y1["Завершить или остановить операцию<br/>по принятому правилу"]
    Y1 --> Y2["Оставить питание банка<br/>или выключить по правилу выхода"]
    Y2 --> Y3([Выход из режима стирания])

    ZA --> ZA1[Зафиксировать аварийное завершение]
    ZA1 --> ZA2[Отключить ПЭД]
    ZA2 --> ZA3[Отключить NAND1]
    ZA3 --> ZA4[Отключить NAND2]
    ZA4 --> ZA5([Выход из режима стирания])