%%{init: {'flowchart': {'curve': 'linear'}}}%%
flowchart TD
    A([Вход по CMD_OBSERVE_START]) --> B[Сохранить параметры запуска]
    B --> C[Выбрать активный банк NAND]
    C --> D[Включить питание NAND<br/>если требуется]
    D --> E[Подтвердить наличие питания NAND]
    E --> F[Подготовить сервис записи НИ]
    F --> G[Включить питание ПЭД<br/>если требуется]
    G --> H[Подтвердить наличие питания ПЭД]
    H --> I[Перевести ПЭД в требуемое состояние]
    I --> J[Установить PED_INHIBIT]
    J --> K[Применить trigger config]
    K --> L[Инициализировать runtime-контекст]
    L --> M["session_id++<br/>mode_id = 0"]
    M --> N[Сформировать ТС 'Статус']
    N --> O[Активное наблюдение OBS_ACTIVE]

    O --> P{"Событие в режиме OBSERVE"}

    P -- "RTC_1HZ" --> Q[Обработка тика 1 Гц]
    P -- "PED_TG<br/>регистрация разрешена" --> R[Обработка события ПЭД]
    P -- "TLM_TIME_SYNC<br/>TLM_ORBIT<br/>TLM_ATTITUDE<br/>TLM_MAGFIELD" --> S[Обработка КТ]
    P -- "CMD_OBSERVE_CTRL" --> T[Изменение конфигурации режима]
    P -- "CMD_TELEM_REQ" --> U["Выдать ТС 'Квитанция'<br/>Выдать ТС 'Телеметрия'"]
    P -- "CMD_STATUS_REQ" --> V["Выдать ТС 'Квитанция'<br/>Выдать ТС 'Статус'"]

    P -. "CMD_DUTY" .-> W[Командное завершение режима]
    P -. "CMD_SHUTDOWN" .-> X[Завершение режима<br/>с переходом в SHUTDOWN]
    P -. "NAND_FULL" .-> Y[Завершение по переполнению NAND]
    P -. "MaskedAlarm != 0" .-> Z[Аварийное завершение режима]

    Q --> Q1[Закрыть предыдущий секундный интервал]
    Q1 --> Q2["Сформировать формат 'Счётчики'"]
    Q2 --> Q3["Сформировать формат 'Спектр-1'<br/>или 'Спектр-2'<br/>если включен"]
    Q3 --> Q4["Сформировать формат 'Телеметрия'<br/>если наступил 20-с интервал<br/>или установлен флаг"]
    Q4 --> Q5[Сбросить секундные накопители]
    Q5 --> O

    R --> R1[Считать событие из ПЭД]
    R1 --> R2[Обновить секундные счётчики]
    R2 --> R3[Обновить гистограмму]
    R3 --> R4["Добавить событие в формат 'События'<br/>если требуется"]
    R4 --> R5[Сформировать PED_TGRES]
    R5 --> O

    S --> S0{"Тип КТ"}
    S0 -- "TLM_TIME_SYNC" --> S1["Сформировать формат 'Синхронизация'"]
    S0 -- "TLM_ORBIT" --> S2["Сформировать формат 'Орбита'"]
    S0 -- "TLM_ATTITUDE" --> S3["Сформировать формат 'Ориентация'"]
    S0 -- "TLM_MAGFIELD" --> S4["Сформировать формат 'Геомагнитное поле'"]
    S1 --> S5[Записать формат в поток НИ]
    S2 --> S5
    S3 --> S5
    S4 --> S5
    S5 --> O

    T --> T1[Обновить конфигурацию ПЭД]
    T1 --> T2[Обновить параметры наблюдений]
    T2 --> T3["mode_id++"]
    T3 --> T4["Установить флаг внеочередного<br/>формата 'Телеметрия'"]
    T4 --> O

    U --> O
    V --> O

    W --> W1[Запретить запуск новых действий режима]
    W1 --> W2["Завершить режим по принятому правилу<br/>командного завершения"]
    W2 --> W3["Сформировать ТС 'Статус'"]
    W3 --> W4([Выход из OBSERVE в DUTY])

    X --> X1[Запретить запуск новых действий режима]
    X1 --> X2["Завершить режим по принятому правилу<br/>выхода в SHUTDOWN"]
    X2 --> X3["Сформировать ТС 'Статус'"]
    X3 --> X4([Выход из OBSERVE в SHUTDOWN])

    Y --> Y1[Запретить запуск новых форматов]
    Y1 --> Y2["Завершить текущую согласованную запись"]
    Y2 --> Y3[Установить признак переполнения банка]
    Y3 --> Y4["Привести ПЭД и NAND<br/>к конфигурации завершения"]
    Y4 --> Y5["Сформировать ТС 'Статус'"]
    Y5 --> Y6([Выход из OBSERVE в DUTY])

    Z --> Z1[Запретить регистрацию событий в ПЭД]
    Z1 --> Z2[Отключить питание ПЭД]
    Z2 --> Z3[Отключить питание NAND1]
    Z3 --> Z4[Отключить питание NAND2]
    Z4 --> Z5["Сформировать ТС 'Статус'"]
    Z5 --> Z6([Выход из OBSERVE в ALARM])