flowchart TD
    A([Вход по CMD_TEST]) --> B[Сохранить параметры команды]
    B --> C[Выбрать банк NAND1 или NAND2]
    C --> D[Включить питание выбранного банка<br/>если требуется]
    D --> E[Подтвердить наличие питания банка]
    E --> F[Подготовить сервис NAND к тесту]
    F --> G["Очистить массив Nerr[2048]"]
    G --> H[Подготовить буферы тестирования]
    H --> I[Сформировать ТС 'Статус']
    I --> J[Начать фазу TEST_WRITE]

    J --> K[Запись тестовой последовательности]
    K --> L{"Запись завершена?"}
    L -- Да --> M[Начать фазу TEST_READ]
    L -- Нет --> K

    K -. "Ошибка записи<br/>или ошибка QSPI" .-> ZA[Аварийное завершение]
    K -. "CMD_DUTY" .-> Y[Завершение по команде]
    K -. "CMD_SHUTDOWN" .-> X[Завершение с переходом в SHUTDOWN]
    K -. "MaskedAlarm != 0" .-> ZA

    M --> N[Чтение тестовых данных]
    N --> O{"Чтение завершено?"}
    O -- Да --> P[Начать фазу TEST_COMPARE]
    O -- Нет --> N

    N -. "Ошибка чтения<br/>или ошибка QSPI" .-> ZA
    N -. "CMD_DUTY" .-> Y
    N -. "CMD_SHUTDOWN" .-> X
    N -. "MaskedAlarm != 0" .-> ZA

    P --> Q[Сравнение записанного и считанного]
    Q --> R["Заполнение массива Nerr"]
    R --> S{"Сравнение завершено?"}
    S -- Да --> T[Начать фазу TEST_SAVE]
    S -- Нет --> Q

    Q -. "Ошибка сравнения" .-> ZA
    R -. "CMD_DUTY" .-> Y
    R -. "CMD_SHUTDOWN" .-> X
    R -. "MaskedAlarm != 0" .-> ZA

    T --> U[Записать Nerr в MRAM]
    U --> V{"Сохранение завершено?"}
    V -- Да --> W[Начать фазу TEST_ERASE]
    V -- Нет --> U

    U -. "Ошибка MRAM" .-> ZA
    U -. "CMD_DUTY" .-> Y
    U -. "CMD_SHUTDOWN" .-> X
    U -. "MaskedAlarm != 0" .-> ZA

    W --> W1[Стереть протестированный банк NAND]
    W1 --> W2{"Стирание завершено?"}
    W2 -- Да --> Z[Штатное завершение]
    W2 -- Нет --> W1

    W1 -. "Ошибка стирания<br/>или ошибка QSPI" .-> ZA
    W1 -. "CMD_DUTY" .-> Y
    W1 -. "CMD_SHUTDOWN" .-> X
    W1 -. "MaskedAlarm != 0" .-> ZA

    Z --> Z1[Обновить результаты последнего теста]
    Z1 --> Z2["Счётчик тестов++"]
    Z2 --> Z3[Обновить служебные данные в MRAM]
    Z3 --> Z4["Оставить питание банка включённым<br/>или отключить по команде"]
    Z4 --> Z5["Сформировать ТС 'Статус'"]
    Z5 --> Z6([Выход из TEST в DUTY])

    Y --> Y1["Завершить режим по принятому правилу<br/>досрочного завершения"]
    Y1 --> Y2["Оставить питание банка включённым<br/>или отключить по правилу выхода"]
    Y2 --> Y3["Сформировать ТС 'Статус'"]
    Y3 --> Y4([Выход из TEST в DUTY])

    X --> X1["Завершить режим по принятому правилу<br/>выхода в SHUTDOWN"]
    X1 --> X2["Оставить питание банка включённым<br/>или отключить по правилу выхода"]
    X2 --> X3["Сформировать ТС 'Статус'"]
    X3 --> X4([Выход из TEST в SHUTDOWN])

    ZA --> ZA1[Прекратить выполнение тестовой последовательности]
    ZA1 --> ZA2[Отключить питание ПЭД]
    ZA2 --> ZA3[Отключить питание NAND1]
    ZA3 --> ZA4[Отключить питание NAND2]
    ZA4 --> ZA5["Сформировать ТС 'Статус'"]
    ZA5 --> ZA6([Выход из TEST в ALARM])